### ISSUE TITLE
index doesn't seem used in the code?

### ISSUE THREAD

**Issue by andersekdahl** [alexanbj/pino-splunk#2]
I'm trying to send pino logs to Splunk and wanted to use this library since it doesn't require the use of stdout but is using programmatic configuration instead.

But when I looked at the code the `index` property on the options object is mandatory, but I can't see where it's being used? Isn't it supposed to be sent as part of the payload to Splunk? That is, shouldn't it be set here along with `source`? https://github.com/alexanbj/pino-splunk/blob/main/src/lib.ts#L99

**Comment by alexanbj** [comment]
This should be fixed in [0.4.1](https://www.npmjs.com/package/pino-splunk/v/0.4.1)

**Comment by andersekdahl** [comment]
Thanks! Should perhaps `index` and `source` be optional as well? They seem to be optional in the Splunk docs:
https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector
